import "./globals.css";
import { Inter, Creepster, Rubik_Wet_Paint } from '@next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
})

const creepster = Creepster({
  subsets: ['latin'],
  weight: [ '400'],
  variable: "--font-creepster",
})

const rubik = Rubik_Wet_Paint({
  subsets: ['latin'],
  weight: [ '400'],
  variable: "--font-rubik",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} ${creepster.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
