import { Analytics } from '@vercel/analytics/react';
import { Creepster, Inter, Rubik_Wet_Paint } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
})

const creepster = Creepster({
  subsets: ['latin'],
  weight: ['400'],
  variable: "--font-creepster",
})

const rubik = Rubik_Wet_Paint({
  subsets: ['latin'],
  weight: ['400'],
  variable: "--font-rubik",
})

export const metadata = {
  title: "Halloween Prank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} ${creepster.variable} ${rubik.variable} antialiased`}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
